# Generated by Django 4.0.4 on 2022-05-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='firstName',
            field=models.CharField(default='sefineh', max_length=50),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='lastName',
            field=models.CharField(default='tesfa', max_length=50),
        ),
        migrations.AlterField(
            model_name='registermodel',
            name='userName',
            field=models.CharField(default='sefineh', max_length=50),
        ),
    ]
