# Generated by Django 4.0.4 on 2022-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0002_alter_registermodel_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registermodel',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
